//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

pub mod prelude;

pub mod dm_hospital;
pub mod dm_instrument;
pub mod dm_mc_sample;
pub mod dm_mc_sample_result;
pub mod regent;
pub mod regent_group;
pub mod sys_dict_data;
pub mod sys_dict_type;
