//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

pub use super::{
    dm_hospital::Entity as DmHospital, dm_instrument::Entity as DmInstrument, dm_mc_sample::Entity as DmMcSample, dm_mc_sample_result::Entity as DmMcSampleResult,
    regent::Entity as Regent, regent_group::Entity as RegentGroup, sys_dict_data::Entity as SysDictData, sys_dict_type::Entity as SysDictType,
};
