//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

pub use super::{regent::Entity as Regent, regent_group::Entity as RegentGroup, sys_dict_data::Entity as SysDictData, sys_dict_type::Entity as SysDictType};
